<?php

namespace ContainerOBfvJ3l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_ApiPlatform_DebugResource_Command_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.api_platform.debug_resource.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.debug.api_platform.debug_resource.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:api-resource', [], 'Debug API Platform resources', false, #[\Closure(name: 'debug.api_platform.debug_resource.command', class: 'ApiPlatform\\Symfony\\Bundle\\Command\\DebugResourceCommand')] fn (): \ApiPlatform\Symfony\Bundle\Command\DebugResourceCommand => ($container->privates['debug.api_platform.debug_resource.command'] ?? $container->load('getDebug_ApiPlatform_DebugResource_CommandService')));
    }
}
