<?php

namespace ContainerOBfvJ3l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProvider_ParameterValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'api_platform.state_provider.parameter_validator' shared service.
     *
     * @return \ApiPlatform\Symfony\Validator\State\ParameterValidatorProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/ParameterParserTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Validator/State/ParameterValidatorProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Security/State/AccessCheckerProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Validator/State/ValidateProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Provider/DeserializeProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Provider/SecurityParameterProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Bundle/SwaggerUi/SwaggerUiProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/OperationRequestInitiatorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Provider/ReadProvider.php';

        $a = ($container->privates['api_platform.openapi.serializer_context_builder'] ?? $container->load('getApiPlatform_Openapi_SerializerContextBuilderService'));

        $b = new \ApiPlatform\State\Provider\ReadProvider(($container->privates['api_platform.state_provider.locator'] ?? self::getApiPlatform_StateProvider_LocatorService($container)), $a);

        $c = ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true));

        if ($container->has('debug.stopwatch')) {
            $b->setStopwatch($c);
        }
        $d = ($container->privates['api_platform.security.resource_access_checker'] ?? self::getApiPlatform_Security_ResourceAccessCheckerService($container));

        $e = new \ApiPlatform\State\Provider\DeserializeProvider(new \ApiPlatform\State\Provider\SecurityParameterProvider(new \ApiPlatform\Symfony\Security\State\AccessCheckerProvider(new \ApiPlatform\Symfony\Bundle\SwaggerUi\SwaggerUiProvider(new \ApiPlatform\Symfony\Security\State\AccessCheckerProvider($b, $d, 'pre_read'), ($container->privates['api_platform.openapi.factory'] ?? $container->load('getApiPlatform_Openapi_FactoryService'))), $d), $d), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)), $a, ($container->services['translator'] ?? self::getTranslatorService($container)));
        if ($container->has('debug.stopwatch')) {
            $e->setStopwatch($c);
        }

        return $container->services['api_platform.state_provider.parameter_validator'] = new \ApiPlatform\Symfony\Validator\State\ParameterValidatorProvider(($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)), new \ApiPlatform\Symfony\Security\State\AccessCheckerProvider(new \ApiPlatform\Symfony\Validator\State\ValidateProvider(new \ApiPlatform\Symfony\Security\State\AccessCheckerProvider($e, $d, 'post_denormalize'), ($container->privates['api_platform.validator'] ?? $container->load('getApiPlatform_ValidatorService'))), $d, 'post_validate'));
    }
}
