<?php

namespace Container6UGtNdQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_ValidateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.validate' shared service.
     *
     * @return \ApiPlatform\Symfony\Validator\State\ValidateProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Validator/State/ValidateProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/StopwatchAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/WriteProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/SerializeProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/http-cache/State/AddHeadersProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/AddLinkHeaderProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/CorsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/hydra/State/HydraLinkProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseHeadersTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/HttpResponseStatusTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Processor/RespondProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/CallableProcessor.php';

        $a = new \ApiPlatform\State\Processor\RespondProcessor(($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container)), ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), ($container->privates['api_platform.metadata.operation.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Operation_MetadataFactory_CachedService($container)), ($container->privates['api_platform.doctrine.orm.metadata.resource.metadata_collection_factory'] ?? self::getApiPlatform_Doctrine_Orm_Metadata_Resource_MetadataCollectionFactoryService($container)));

        $b = ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true));

        if ($container->has('debug.stopwatch')) {
            $a->setStopwatch($b);
        }

        $c = new \ApiPlatform\State\Processor\AddLinkHeaderProcessor(new \ApiPlatform\Hydra\State\HydraLinkProcessor($a, ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container))));
        if ($container->has('debug.stopwatch')) {
            $c->setStopwatch($b);
        }

        $d = new \ApiPlatform\State\Processor\SerializeProcessor(new \ApiPlatform\HttpCache\State\AddHeadersProcessor($c, true, NULL, NULL, $container->parameters['api_platform.http_cache.vary'], NULL, NULL, NULL), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)), ($container->privates['api_platform.openapi.serializer_context_builder'] ?? $container->load('getApiPlatform_Openapi_SerializerContextBuilderService')));
        if ($container->has('debug.stopwatch')) {
            $d->setStopwatch($b);
        }

        $e = new \ApiPlatform\State\Processor\WriteProcessor($d, new \ApiPlatform\State\CallableProcessor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'api_platform.swagger_ui.processor' => ['privates', 'api_platform.swagger_ui.processor', 'getApiPlatform_SwaggerUi_ProcessorService', true],
            'api_platform.doctrine.orm.state.remove_processor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'api_platform.doctrine.orm.state.persist_processor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => ['privates', 'api_platform.doctrine.orm.state.remove_processor', 'getApiPlatform_Doctrine_Orm_State_RemoveProcessorService', true],
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => ['privates', 'api_platform.doctrine.orm.state.persist_processor', 'getApiPlatform_Doctrine_Orm_State_PersistProcessorService', true],
            'ApiPlatform\\Symfony\\Messenger\\Processor' => ['privates', 'ApiPlatform\\Symfony\\Messenger\\Processor', 'getProcessorService', true],
        ], [
            'api_platform.swagger_ui.processor' => 'ApiPlatform\\Symfony\\Bundle\\SwaggerUi\\SwaggerUiProcessor',
            'api_platform.doctrine.orm.state.remove_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'api_platform.doctrine.orm.state.persist_processor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\RemoveProcessor',
            'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor' => 'ApiPlatform\\Doctrine\\Common\\State\\PersistProcessor',
            'ApiPlatform\\Symfony\\Messenger\\Processor' => 'ApiPlatform\\Symfony\\Messenger\\Processor',
        ])));
        if ($container->has('debug.stopwatch')) {
            $e->setStopwatch($b);
        }

        return $container->privates['api_platform.state_processor.validate'] = new \ApiPlatform\Symfony\Validator\State\ValidateProcessor($e, ($container->privates['api_platform.validator'] ?? $container->load('getApiPlatform_ValidatorService')));
    }
}
