<?php

namespace Container6UGtNdQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Doctrine_Orm_LinksHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.doctrine.orm.links_handler' shared service.
     *
     * @return \ApiPlatform\Doctrine\Orm\State\LinksHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/State/LinksHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/State/LinksHandlerTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/State/LinksHandlerTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/State/LinksHandler.php';

        $a = ($container->privates['api_platform.doctrine.orm.metadata.resource.metadata_collection_factory'] ?? self::getApiPlatform_Doctrine_Orm_Metadata_Resource_MetadataCollectionFactoryService($container));

        if (isset($container->privates['api_platform.doctrine.orm.links_handler'])) {
            return $container->privates['api_platform.doctrine.orm.links_handler'];
        }

        $instance = new \ApiPlatform\Doctrine\Orm\State\LinksHandler($a, ($container->services['doctrine'] ?? self::getDoctrineService($container)));

        if (isset($container->privates['api_platform.doctrine.orm.links_handler'])) {
            return $container->privates['api_platform.doctrine.orm.links_handler'];
        }

        return $container->privates['api_platform.doctrine.orm.links_handler'] = $instance;
    }
}
