<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'ApiPlatform_State_ApiResource_Error' => 0,
'ApiPlatform_Validator_Exception_ValidationException' => 1,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'ApiPlatform\\State\\ApiResource\\Error',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'detail' => $o[3],
                    'status' => $o[4],
                    'instance' => $o[5],
                    'type' => $o[6],
                    'headers' => $o[7],
                    'meta' => $o[8],
                    'source' => $o[9],
                    'description' => $o[10],
                    'originalTrace' => $o[11],
                    'message' => $o[12],
                    'code' => $o[13],
                    'file' => $o[14],
                    'line' => $o[15],
                    'statusCode' => $o[16],
                    'string' => $o[17],
                    'trace' => $o[18],
                    'previous' => $o[19],
                    'traceAsString' => $o[20],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'title',
                'detail',
                'status',
                'instance',
                'type',
                'headers',
                'meta',
                'source',
                'description',
                'originalTrace',
                'message',
                'code',
                'file',
                'line',
                'statusCode',
                'string',
                'trace',
                'previous',
                'traceAsString',
            ],
            'groups' => [
                1 => [
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'jsonproblem',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'jsonproblem',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'jsonproblem',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'jsonproblem',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'jsonproblem',
                    'jsonapi',
                ],
                8 => [
                    'jsonapi',
                ],
                [
                    'jsonapi',
                ],
                [
                    'jsonld',
                ],
                [
                    'trace',
                ],
            ],
            'ignore' => [
                7 => true,
                16 => true,
            ],
            'serializedName' => [
                11 => 'trace',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'ApiPlatform\\Validator\\Exception\\ValidationException',
            ],
            'attributesMetadata' => [
                [
                    'status' => $o[1],
                    'errorTitle' => $o[2],
                    'constraintViolationList' => $o[3],
                    'detail' => $o[4],
                    'message' => $o[5],
                    'code' => $o[6],
                    'file' => $o[7],
                    'line' => $o[8],
                    'id' => $o[9],
                    'description' => $o[10],
                    'type' => $o[11],
                    'title' => $o[12],
                    'instance' => $o[13],
                    'statusCode' => $o[14],
                    'headers' => $o[15],
                    'string' => $o[16],
                    'trace' => $o[17],
                    'previous' => $o[18],
                    'traceAsString' => $o[19],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'status',
                'errorTitle',
                'constraintViolationList',
                'detail',
                'message',
                'code',
                'file',
                'line',
                'id',
                'description',
                'type',
                'title',
                'instance',
                'statusCode',
                'headers',
                'string',
                'trace',
                'previous',
                'traceAsString',
            ],
            'groups' => [
                1 => [
                    'jsonld',
                    'json',
                    'jsonapi',
                ],
                3 => [
                    'json',
                    'jsonld',
                ],
                [
                    'jsonld',
                    'json',
                    'jsonapi',
                ],
                10 => [
                    'jsonld',
                ],
                [
                    'jsonld',
                    'json',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'json',
                    'jsonapi',
                ],
                [
                    'jsonld',
                    'json',
                    'jsonapi',
                ],
            ],
            'serializedName' => [
                3 => 'violations',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
